SIZE = 400
END_SCORE = 4000
GRID_LEN = 3
WINAT = 2048
GRID_PADDING = 10
CHROMOSOME_LEN = 2*pow(GRID_LEN, 4) + 8*GRID_LEN*GRID_LEN

TOURNAMENT_SELECTION_SIZE = 4
MUTATION_RATE = 0.25
NUMBER_OF_ELITE_CHROMOSOMES = 3
POPULATION_SIZE = 10
GEN_MAX = 10000
DONOTHINGINPUT_MAX = 5

BACKGROUND_COLOR_GAME = "#92877d"
BACKGROUND_COLOR_CELL_EMPTY = "#9e948a"

FONT = ("Verdana", 40, "bold")

KEY_UP_ALT = "\'\\uf700\'"
KEY_DOWN_ALT = "\'\\uf701\'"
KEY_LEFT_ALT = "\'\\uf702\'"
KEY_RIGHT_ALT = "\'\\uf703\'"

KEY_UP = 'w'
KEY_DOWN = 's'
KEY_LEFT = 'a'
KEY_RIGHT = 'd'
KEY_BACK = 'b'

KEY_J = "'j'"
KEY_K = "'k'"
KEY_L = "'l'"
KEY_H = "'h'"
